Models/Booking.cs
namespace HouseRenting.Models
{
    public class Booking
    {
        public int BookingId { get; set; }
        public string BookingDate { get; set; } = String.Empty;
        
        public int CustomerId { get; set; }
        public virtual Customer Customer { get; set; } = default!;

        public int ItemId { get; set; }
        public virtual Item? Items { get; set; }
    }
}

Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace HouseRenting.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }

        [RegularExpression(@"[0-9a-zA-ZæøåÆØÅ. \-]{2,20}", ErrorMessage = "The Name must be numbers or letters and between 2 to 20 characters.")]
        [Display(Name = "Customer.Name")]
        public string Name { get; set; } = String.Empty;

        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", ErrorMessage = "Ugyldig e - postadresse")]
        [Display(Name = "Customer.Email")]
        public string Email { get; set; } = String.Empty;

        [RegularExpression(@"^\+?(?:[0-9] ?){4,14}[0-9]$", ErrorMessage = "Invalid phone number")]
        [Display(Name = "Customer.Phone")]
        public string Phone { get; set; }= String.Empty;
        public virtual List<Booking>? Bookings { get; set; }
    }
}

Models/Item.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;
namespace HouseRenting.Models
{
    public class Item
    {
           public int ItemId { get; set; }
        public string Category { get; set; } = string.Empty;
        public string Location { get; set; } = string.Empty;

        [Range(1,24, ErrorMessage = "The numbers of rooms must be greater than 0.and less then 20")]
        public int Rooms { get; set; }

        [Range(5, int.MaxValue, ErrorMessage = "The Area must be greater than 5m.")]
        public int Area {get; set; }
        [Range(500, int.MaxValue, ErrorMessage = "The Renting must be greater than 500 kr.")]
        public int Renting { get; set; }

        [StringLength(300)]
        public string? Description { get; set; }
        public string? ImageUrl { get; set; }

        public bool IsBooked { get; set; } = false;
        public virtual List<Image>? Images { get; set; }
        public virtual Booking? Bookings { get; set; }


    }
}

Controllers/BookingController.cs
using HouseRenting.DAL;
using HouseRenting.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging; 
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using HouseRenting.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace HouseRenting.Controllers
{
    public class BookingController : Controller
    {
        private readonly IBookingRepository _bookingRepository;
        private readonly ILogger<BookingController> _logger;
        private readonly ItemDbContext _itemDbContext;

        public BookingController(ItemDbContext itemDbContext, IBookingRepository bookingRepository, ILogger<BookingController> logger)
        {
            _itemDbContext = itemDbContext;
            _bookingRepository = bookingRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Table()
        {
            string loggedInUserEmail = User.FindFirstValue(ClaimTypes.Email);
            List<Booking> bookings = await _itemDbContext.Bookings
                .Where(b => b.Customer.Email == loggedInUserEmail)
                .ToListAsync();
            return View(bookings);
        }
        public async Task<IActionResult> AllBookingsTable()
        {
            //string loggedInUserEmail = User.Identity.Name;
            List<Booking> allBookings = await _itemDbContext.Bookings        
                .ToListAsync();
            return View(allBookings);
        }


        [HttpGet]
        [Authorize]
        public IActionResult CreateBookingItem(int itemId)
        {
            // Fetch the Item using the itemId
            var item = _itemDbContext.Items.FirstOrDefault(i => i.ItemId == itemId);

            if (item == null)
            {
                // Handle the case where the item is not found, maybe return a 404 or redirect
                return NotFound();
            }

            // Create a new Booking object and set its ItemId
            Booking booking = new Booking { ItemId = itemId };

            // Create the view model
            var viewModel = new CreateBookingViewModel
            {
                Item = item,
                Booking = booking
            };

            
            return View(viewModel);
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateBookingItem(Booking booking, int itemId)
        {
            // Fetch the Item using the itemId
            var item = _itemDbContext.Items.FirstOrDefault(i => i.ItemId == itemId);

            // Create the view model
            var viewModel = new CreateBookingViewModel
            {
                Item = item,
                Booking = booking
            };

            if (ModelState.IsValid)
            {
                // Check if booking was created successfully
                bool isBookingCreated = await _bookingRepository.CreateBookingItem(booking, itemId);

                if (isBookingCreated)
                {
                    booking.Items.IsBooked = true;

                    await _itemDbContext.SaveChangesAsync();
                    // Table message
                    string tableHtml = $"<table class=\"table table-striped\">" +
                        $"<tr><th>House number</th><th>Customer Name</th><th>Booking Date</th></tr>" +
                        $"<tr><td>{booking.ItemId}</td><td>{booking.Customer.Name}</td><td>{booking.BookingDate}</td></tr>" +
                        $"</table>";

                    TempData["BookingTable"] = tableHtml;

                    // Confirmation message without the table
                    string confirmationMessage = $"We confirm that Huset nummer {booking.ItemId} er booket av {booking.Customer.Name} in the date:{booking.BookingDate}!";

                    TempData["BookingConfirmation"] = confirmationMessage;

                    // Redirect to Receipt view
                    return View("Receipt", viewModel);
                }
            }

            // If there are validation errors or booking creation failed, set ModelState for ItemId and return to the same view with the validation errors
            _logger.LogWarning("[BookingController] Booking creation failed", booking);

          

            return View("CreateBookingItem", viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var booking = await _bookingRepository.GetBookingById(id);
            if (booking == null)
            {
                _logger.LogError("[BookingController] Booking not found for the BookingId {BookingId:0000}", id);
                return BadRequest("Booking not found for the BookingId");
            }
            return View(booking);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool Ok = await _bookingRepository.Delete(id);
            if (!Ok)
            {
                _logger.LogError("[BookingController] Booking deletion failed for the  BookingId { BookingId:0000}", id);
                return BadRequest(" Booking deletion failed");
            }
            return RedirectToAction(nameof(Table));
        }

       
    }
}

Controllers/CustomerController.cs
using HouseRenting.DAL;
using HouseRenting.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Claims;

namespace HouseRenting.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ItemDbContext _itemDbContext;
        private readonly ICustomerRepository _customerRepository;
        private readonly ILogger<CustomerController> _logger; 

        public CustomerController(ItemDbContext itemDbContext, ICustomerRepository customerRepository, ILogger<CustomerController> logger)
        {
            _itemDbContext = itemDbContext;
            _customerRepository = customerRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Table()
        {

            string loggedInUserEmail = User.FindFirstValue(ClaimTypes.Email);


            List<Customer> customers = await _itemDbContext.Customers
                .Where(c => c.Email == loggedInUserEmail)
                .ToListAsync();

            return View(customers);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> AllCustomersTable()
        {
            //string loggedInUserEmail = User.Identity.Name;
            List<Customer> allCustomers = await _itemDbContext.Customers
                 .ToListAsync();
            return View(allCustomers);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DeleteCustomer(int id)
        {
            var customer = await _customerRepository.GetCustomerById(id);
            if (customer == null)
            {
                _logger.LogError("[CustomerController] Customer not found for the CustomerId {CustomerId:0000}", id);
                return BadRequest("Customer not found for the CustomerId");
            }
            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCustomerConfirmed(int id)
        {
            bool ok = await _customerRepository.DeleteCustomer(id);
            if (!ok)
            {
                _logger.LogError("[CustomerController] Customer deletion failed for the CustomerId { CustomerId:0000}", id);
                return BadRequest("Customer deletion failed");
            }
            return RedirectToAction(nameof(Table));
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DeleteAllCustomers()
        {
            var customers = await _customerRepository.GetAll();
            if (customers == null)
            {
                _logger.LogError("[CustomerController] Customers not found");
                return BadRequest("Customers not found");
            }

            return View("DeleteAllCustomersConfirmation");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAllCustomersConfirmed()
        {
            bool ok = await _customerRepository.DeleteAllCustomers();

            if (!ok)
            {
                _logger.LogError("[CustomerController] Customers deletion failed ");
                return BadRequest("Customer deletion failed");
            }

            return RedirectToAction(nameof(AllCustomersTable));
        }

    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using HouseRenting.Models;
using HouseRenting.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using HouseRenting.DAL;
using Microsoft.AspNetCore.Authorization;


namespace HouseRenting.Controllers

{
    public class ItemController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly ILogger<ItemController> _logger;
        public ItemController(IItemRepository itemRepository, ILogger<ItemController> logger)
        {
            _itemRepository = itemRepository;
            _logger = logger;
        }
        //public List<Booking> BookingConsole(){return _itemDbContext.Bookings.ToList();}
        public async Task<IActionResult> Table()
        {
            var items = await _itemRepository.GetAll();
            if (items == null)
            {
                _logger.LogError("[ItemController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            var itemListViewModel = new ItemListViewModel(items, "Table");
            return View(itemListViewModel);
        }
        public async Task<IActionResult> Details(int id)
        {
            var item = await _itemRepository.GetItemById(id);
            if (item == null)
            {
                _logger.LogError("[ItemController] Item not found for the ItemId {ItemId:0000}", id);
                return NotFound("Item not found for the ItemId");
            }
            return View(item);
        }
        public async Task<IActionResult> Grid()
        {
            var items = await _itemRepository.GetAll();
            if (items == null)
            {
                _logger.LogError("[ItemController] Item list not found while executing _itemRepository.GetAll()");
                return NotFound("Item list not found");
            }
            var itemListViewModel = new ItemListViewModel(items, "Grid");
            return View(itemListViewModel);
        }
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Item item)
        {
            if (ModelState.IsValid)
            {
                bool Ok = await _itemRepository.Create(item);
                if (Ok)
                    return RedirectToAction(nameof(Table));
            }
            _logger.LogWarning("[ItemController] Item creation failed {@item}", item);
            return View(item);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Update(int id)
        {
            var item = await _itemRepository.GetItemById(id);
            if (item == null) 
            {
                _logger.LogError("[ItemController] Item not found when updating the ItemId {ItemId:0000}", id);
                return BadRequest("Item not found for the ItemId");
            }
            return View(item);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Update(Item item)
        {
            if (ModelState.IsValid)
            {
                bool Ok = await _itemRepository.Update(item);
                if (Ok)
                    return RedirectToAction(nameof(Table));
            }
            _logger.LogWarning("[ItemController] Item update failed {@item}", item);
            return View(item);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var item = await _itemRepository.GetItemById(id);
            if (item == null)
            {
                _logger.LogError("[ItemController] Item not found for the ItemId {ItemId:0000}", id);
                return BadRequest("Item not found for the ItemId");
            }
            return View(item);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool Ok = await _itemRepository.Delete(id);
            if (!Ok)
            {
                _logger.LogError("[ItemController] Item deletion failed for the ItemId {ItemId:0000}", id);
                return BadRequest("Item deletion failed");
            }
            return RedirectToAction(nameof(Table));
        }

    }
}

Views/Shared/_BookingTable.cshtml
@model IEnumerable<HouseRenting.Models.Booking>
<div class="container" id="booking">
    <h1>List of Bookings</h1>
     @foreach (var booking in Model)
        {
            <div class="container bg-light">
            <p class="text-primary">Booking @booking.BookingId</p>
            <table class="table table-striped">
                <tr>
                    <th>HousseNr</th>
                    <th>Location</th>
                    <th>CustomerId</th>
                    <th>Customer Name</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                <tr>
                    <td>@booking.ItemId</td>
                    <td>@(booking.Items?.Location ?? "No Location")</td>
                    <td>@booking.Customer.CustomerId</td>
                    <td>@booking.Customer.Name</td>
                    <td>@booking.BookingDate</td>
                    <td>
                        <p>
                            <a class="btn btn-outline-danger" asp-route-id="@booking.BookingId"
                               asp-controller="Booking"
                               asp-action="Delete">Delete this Booking</a>
                        </p>

                    </td>
                </tr>

            </table>
           </div>
        }
</div>

Views/Shared/_CustomerTable.cshtml
@model IEnumerable<HouseRenting.Models.Customer>
<div class="container">
    <h1>List of Customers</h1>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Booking</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
        @foreach (var c in Model)
        {
            <tr>
                <td>@c.CustomerId</td>
                <td>@c.Name</td>
                <td>@c.Email</td>
                <td>@c.Phone</td>
                @if (c.Bookings != null)
                {
                    <td> <p>@string.Join(", ", c.Bookings.Select(booking => $"House {booking.ItemId}"))</p> </td>
                    <td> <p>@string.Join(", ", c.Bookings.Select(booking => $"{booking.BookingDate}"))</p></td>
                }
                <td>
                    <p>
                        <a class="btn btn-outline-danger" asp-route-id="@c.CustomerId"
                           asp-controller="Customer"
                           asp-action="DeleteCustomer">Delete this Booking</a>
                    </p>
                </td>
            </tr>
        }
    </table>
</div>

Views/Shared/_ItemCard.cshtml
<div class="col-md-4 mb-4">
    <div class="card h-100 bg-light card-animation" style="border-radius: 5%">
        <a href="@Url.Action("Details", "Item", new { id = Model.ItemId })" class="text-decoration-none text-dark">
            <div style="position: relative; overflow: hidden; height: 200px;">
                <img src="@Model.ImageUrl" class="card-img-top" aria-hidden="true" alt="@Model.Category" style="position: absolute; object-fit: cover; height: 100%; width: 100%; border-radius: 5%">
            </div>
            <div class="card-body">
                <h5 class="card-title">@Model.Category</h5>
                <div class="d-flex justify-content-between">
                    <p class="card-text">@Model.Renting.ToString("0.00 NOK")</p>
                    
                    @if (Model.IsBooked == true)
                    {
                        <p class="card-text btn btn-danger" style="text-align: right;">Booked</p>
                    }
                </div>
                
            </div>
        </a>
    </div>
    
</div>

Views/Shared/_ItemTable.cshtml
@model IEnumerable<HouseRenting.Models.Item>
<div class="container">
    <h1>@ViewBag.CurrentViewName</h1>
    <table class="table table-hover">
        <tr>
            <th>Id</th>
            <th>Category</th>
            <th>Rooms</th>
            <th>Area</th>
            <th>Renting</th>
            <th>Images</th>
            <th>Actions</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td onclick="location.href='@Url.Action("Details", "Item", new { id = item.ItemId })';" style="cursor:pointer;">@item.ItemId</td>
                <td onclick="location.href='@Url.Action("Details", "Item", new { id = item.ItemId })';" style="cursor:pointer;">@item.Category</td>
                <td onclick="location.href='@Url.Action("Details", "Item", new { id = item.ItemId })';" style="cursor:pointer;">@item.Rooms</td>
                <td onclick="location.href='@Url.Action("Details", "Item", new { id = item.ItemId })';" style="cursor:pointer;">@item.Area</td>
                <td onclick="location.href='@Url.Action("Details", "Item", new { id = item.ItemId })';" style="cursor:pointer;">@item.Renting.ToString("0.00 NOK")</td>
                <td onclick="location.href='@Url.Action("Details", "Item", new { id = item.ItemId })';" style="cursor:pointer;">
                    @if (!string.IsNullOrEmpty(item.ImageUrl))
                    {
                        
                            <img src="@item.ImageUrl" alt="Item Image" style="max-width: 100px; max-height: 100px;" />
                        
                    }
                    else
                    {
                        <span>No Image</span>
                    }
                </td>
                <td>
                    <a asp-action="Update" asp-route-id="@item.ItemId" class="btn btn-outline-success">Update</a>
                    <a asp-action="Delete" asp-route-id="@item.ItemId" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
        }
    </table>
    <p>
        <a class="btn btn-outline-primary"
        asp-controller="Item"
        asp-action="Create">New House</a>
        
        @*<a class="btn btn-outline-secondary" asp-area=""
        asp-action="BookingConsole" target="_blank">Console Bookings</a>*@
    </p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>HRS</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Gp
    * Updated: Sep 18 2023 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top ">
        <div class="container d-flex align-items-center justify-content-lg-between">

            <h1 class="logo me-auto me-lg-0"><a href="index.html">HRS<span>.</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="~/assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto active" href="/Home/Index">Home</a></li>
                    <li><a class="nav-link scrollto" href="#services">Categories</a></li>
                    <li><a class="nav-link scrollto" href="/Item/Grid">Houses</a></li>

                    <li class="dropdown">
                        <a href="#"><span>More</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="/Booking/Table">My Bookings</a></li>
                            <li><a href="/Customer/Table">My Info</a></li>
                            <li><a asp-action="AllCustomersTable" asp-controller="Customer">All Customers</a></li>
                            <li><a asp-action="AllBookingsTable" asp-controller="Booking">All Bookings</a></li>
                            <li><a href="#about">About Us</a></li>
                            <li><a href="#contact">Contact Us</a></li>

                        </ul>
                    </li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <partial name="_LoginPartial" />

        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center justify-content-center">
        <div class="container" data-aos="fade-up">

            <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
                <div class="col-xl-6 col-lg-8">
                    <h1>House Renting System <span>.</span></h1>
                    <h2>We are a Web Development Team</h2>
                </div>
            </div>

            <div class="row gy-4 mt-5 justify-content-center" data-aos="zoom-in" data-aos-delay="250">
                <form action="#" class="form-search d-flex align-items-stretch mb-3" data-aos="fade-up" data-aos-delay="200">
                    <input type="text" class="form-control " placeholder="Search in our Houses">
                    <button type="submit" class="btn btn-primary ">Search</button>
                </form>

            </div>

        </div>
    </section><!-- End Hero -->

    <main id="main" >
        <div class="container " style=" margin: 15px; padding:15px">

        @RenderBody()
        @RenderSection("Scripts", required: false)
        </div>





    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer class="bg-light container" style="padding: 15px; margin-top: 10%" >
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <h3>Gp<span>.</span></h3>
                            <p>
                                A108 Adam Street <br>
                                NY 535022, USA<br><br>
                                <strong>Phone:</strong> +1 5589 55488 55<br>
                                <strong>Email:</strong> info@example.com<br>
                            </p>
                            <div class="social-links mt-3">
                                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Gp</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>